import datetime
import os
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
import sys

from peewee import *
from pwiz import *
from playhouse.tests.base import database_initializer
from playhouse.tests.base import mock
from playhouse.tests.base import PeeweeTestCase


db = database_initializer.get_database('sqlite')

class BaseModel(Model):
    class Meta:
        database = db

class User(BaseModel):
    username = CharField(primary_key=True)

class Note(BaseModel):
    user = ForeignKeyField(User)    # non-alphabetical order is important here
    text = TextField(index=True)

class Category(BaseModel):
    parent = ForeignKeyField('self', null=True) # non-alphabetical order is important here
    name = CharField(unique=True)

class capture_output(object):
    def __enter__(self):
        self._stdout = sys.stdout
        sys.stdout = self._buffer = StringIO()
        return self

    def __exit__(self, *args):
        self.data = self._buffer.getvalue()
        sys.stdout = self._stdout

EXPECTED_HEAD = """
from peewee import *

database = SqliteDatabase('peewee_test.db', **{})

class UnknownField(object):
    pass

class BaseModel(Model):
    class Meta:
        database = database

class Category(BaseModel):"""

EXPECTED_CAT_NAME = """
    name = CharField(unique=True)"""

EXPECTED_CAT_PARENT = """
    parent = ForeignKeyField(db_column='parent_id', null=True, rel_model='self', to_field='id')"""

EXPECTED_MID = """

    class Meta:
        db_table = 'category'

class User(BaseModel):
    username = CharField(primary_key=True)

    class Meta:
        db_table = 'user'

class Note(BaseModel):"""

EXPECTED_NOTE_TEXT = """
    text = TextField(index=True)"""

EXPECTED_NOTE_USER = """
    user = ForeignKeyField(db_column='user_id', rel_model=User, to_field='username')"""

EXPECTED_NOTE_END = """

    class Meta:
        db_table = 'note'
"""

EXPECTED = (EXPECTED_HEAD +
            EXPECTED_CAT_NAME +
            EXPECTED_CAT_PARENT +
            EXPECTED_MID +
            EXPECTED_NOTE_TEXT +
            EXPECTED_NOTE_USER +
            EXPECTED_NOTE_END).strip()

EXPECTED_PRESERVE_ORDER =  (EXPECTED_HEAD +
                            EXPECTED_CAT_PARENT +
                            EXPECTED_CAT_NAME +
                            EXPECTED_MID +
                            EXPECTED_NOTE_USER +
                            EXPECTED_NOTE_TEXT +
                            EXPECTED_NOTE_END).strip()

class TestPwiz(PeeweeTestCase):
    def setUp(self):
        super(TestPwiz, self).setUp()
        if os.path.exists(db.database):
            os.unlink(db.database)
        db.connect()
        db.create_tables([User, Note, Category])
        self.introspector = Introspector.from_database(db)

    def tearDown(self):
        super(TestPwiz, self).tearDown()
        db.close()

    def test_print_models(self):
        with capture_output() as output:
            print_models(self.introspector)

        self.assertEqual(output.data.strip(), EXPECTED)

    def test_print_models_order_preserved(self):
        with capture_output() as output:
            print_models(self.introspector, preserve_order=True)

        self.assertEqual(output.data.strip(), EXPECTED_PRESERVE_ORDER)

    def test_print_header(self):
        cmdline = '-i -e sqlite /path/to/database.db'

        with capture_output() as output:
            with mock.patch('pwiz.datetime.datetime') as mock_datetime:
                now = mock_datetime.now.return_value
                now.strftime.return_value = 'February 03, 2015 15:30PM'
                print_header(cmdline, self.introspector)

        self.assertEqual(output.data.strip(), (
            '# Code generated by:\n'
            '# python -m pwiz %s\n'
            '# Date: February 03, 2015 15:30PM\n'
            '# Database: peewee_test.db\n'
            '# Peewee version: %s') % (cmdline, peewee_version))
